export const enum ErrorCode {
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_TOKEN_EXPIRED = 'AUTH_TOKEN_EXPIRED',
  AUTH_INSUFFICIENT_PERMISSIONS = 'AUTH_INSUFFICIENT_PERMISSIONS',
  AUTH_STEP_UP_REQUIRED = 'AUTH_STEP_UP_REQUIRED',

  PROFILE_INCOMPLETE = 'PROFILE_INCOMPLETE',
  PROFILE_DPI_DUPLICATE = 'PROFILE_DPI_DUPLICATE',
  PROFILE_CONSENT_REQUIRED = 'PROFILE_CONSENT_REQUIRED',

  REQUEST_NOT_FOUND = 'REQUEST_NOT_FOUND',
  REQUEST_INVALID_TRANSITION = 'REQUEST_INVALID_TRANSITION',

  PAYMENT_AMOUNT_MISMATCH = 'PAYMENT_AMOUNT_MISMATCH',
  PAYMENT_GATEWAY_ERROR = 'PAYMENT_GATEWAY_ERROR',
  PAYMENT_DUPLICATE = 'PAYMENT_DUPLICATE',

  DOCUMENT_NOT_FOUND = 'DOCUMENT_NOT_FOUND',
  DOCUMENT_EXPIRED = 'DOCUMENT_EXPIRED',
  DOCUMENT_ACCESS_DENIED = 'DOCUMENT_ACCESS_DENIED',

  ADMIN_UNAUTHORIZED = 'ADMIN_UNAUTHORIZED',

  VALIDATION_FAILED = 'VALIDATION_FAILED',

  INTERNAL_ERROR = 'INTERNAL_ERROR',
}
