-- Migration 005: Adapt users table for Auth.js v5 (NextAuth)
-- Auth.js manages its own OAuth lifecycle; we do not use Supabase Auth.
-- The public.users.id FK to auth.users is removed so Auth.js can generate
-- its own UUIDs. google_sub becomes the OAuth identity anchor.
-- All DB operations go through service_role (server-side only).

-- ============================================================
-- Remove auth.users dependency from public.users
-- The FK was added in migration 002 assuming Supabase Auth integration.
-- With Auth.js, we manage the user lifecycle ourselves.
-- ============================================================

ALTER TABLE public.users
  DROP CONSTRAINT IF EXISTS users_id_fkey;

-- Ensure id has a default so Auth.js can insert without supplying a UUID
ALTER TABLE public.users
  ALTER COLUMN id SET DEFAULT gen_random_uuid();

-- ============================================================
-- Add google_sub — the stable OAuth identifier from Google
-- Unique: one Google account maps to one platform user.
-- NOT exposed in API responses (server-side only).
-- ============================================================

ALTER TABLE public.users
  ADD COLUMN IF NOT EXISTS google_sub TEXT UNIQUE;

-- ============================================================
-- Remove the auth.users INSERT trigger (no longer needed)
-- The trigger was created in migration 002 to sync Supabase Auth users.
-- Auth.js upserts directly into public.users via service_role.
-- ============================================================

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
DROP FUNCTION IF EXISTS public.handle_new_auth_user();

-- ============================================================
-- Update RLS policies to reflect the new auth model
-- auth.uid() returns NULL since we are not using Supabase Auth JWTs.
-- Client-side Supabase queries are not used in S2-01; all queries go
-- through service_role. RLS policies are kept for future S2-02 bridge.
-- ============================================================

-- (No RLS policy changes needed in this migration — see S2-02 for
-- Supabase JWT bridge that will re-enable auth.uid()-based policies)

COMMENT ON COLUMN public.users.google_sub IS
  'Google OAuth sub claim. Stable identity anchor from Google. '
  'Server-side only — never exposed in API responses.';

COMMENT ON COLUMN public.users.id IS
  'Internal platform UUID. Generated by Auth.js on first sign-in. '
  'Not linked to auth.users (Auth.js manages user lifecycle, not Supabase Auth).';
